### to create base64 access key run in terminal -> echo -n 'access key from s3' | base64
### to create base64 secret key run in terminal -> echo -n 'secret key from s3' | base64

apiVersion: v1
kind: Secret
metadata:
  name: s3cfg
type: Opaque
data:
  access_key: <Access Key base64>
  secret_key: <Secret Key base64>
